### ISSUE TITLE
Why MySQL?

### ISSUE THREAD

**Issue by afucher** [PadawanTeam/Recommended-Workstation#1]
Why use MySQL and not PostgreSQL?

**Comment by pedrualves** [comment]
So, Pedro's opinion:

The most important objective here, at this point, is show to the new padawans how to configure a startup workstation and how to make a simple web application using nodejs to make rest api integrated on NoSQL db(mongodb), one key:value(redis) db and one SQL db like MySql.

Of course they have differences. And no, I can't say one of them is better and other is a bad choice.

Maybe at step 2 on the "padawan way" we could explain more info, more database types like MariaDB,  PostgreSql, FireBird, Oracle, SqlServer, CouchDB, CouchBase, RethinkDB, Neo4j, DynamoDB, etc...

What you think about this plan @afucher ?

Oh and you prefer PostgreSQL or MySQL?
Let me know...maybe we could make together one more article comparing this guys, based a lot of articles in web? LOLLL

**Comment by pedrualves** [comment]
Anyway, look: [Updated way](https://github.com/PadawanTeam/Recommended-Workstation/blob/master/README.md)
I added more database links to the padawans learn in the future.

**Comment by afucher** [comment]
@pedrualves I'm starting an app and choose PostgreSql as database (for no reason), so I just asked because I want to know your opinion :)

Also I made this [repo](https://github.com/afucher/seq-pg-json) to learn about JSON columns in PostgreSQL

**Comment by pedrualves** [comment]
LOL, very well
